### ISSUE TITLE
Latest daily breaks WebhookDump (and shoko)

### ISSUE THREAD

**Issue by Yankees4life** [fearnlj01/WebhookDump-ShokoPlugin#5]
I had to disable the plugin in order to use the latest daily which broke a lot of existing plugins.

Here's the logs if you need it
https://pastebin.com/Em0Lr8DT

**Comment by fearnlj01** [comment]
Should hopefully have been fixed by #6! (Thanks you @harshithmohan)

Latest build is available [here](https://github.com/fearnlj01/WebhookDump-ShokoPlugin/releases/tag/v0.53).
